### ISSUE TITLE
Firefox can't connect to server?

### ISSUE THREAD

**Issue by elaineo** [elaineo/etherwallet#4]
Non-op in firefox, haven't tested.

**Comment by realcodywburns** [comment]
I tested in in firefox desktop (Linux) it failed to load. 
I reopened firefox in safemode, the page loaded fine. 
Closed and reopened normal, page loads no errors.
Odd behavior....

**Comment by mikeyb** [comment]
Loads in FF for me just fine.

ubuntu 16.04
firefox 48

You all still seeing issues?  Do you see any errors in dev console when it fails?

**Comment by elaineo** [comment]
Maybe close for now, and reopen if it comes up again.
